account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView
from account.views import account_password_change_done, account_password_reset_complete, account_password_reset_done, account_sign_up, account_wishlist
from django.urls import reverse_lazy

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
	path('password_change/', PasswordChangeView.as_view(), {'post_change_redirect' : 'account:password_change_done'}, name='password_change'),
	path('password_change/done/', account_password_change_done, name='password_change_done'),
	path('password_reset/', PasswordResetView.as_view(success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),
	path('password_reset/done/',account_password_reset_done, name='password_reset_done'),
	path('password_reset/confirm/<str:uidb64>/<str:token>/',PasswordResetConfirmView.as_view(success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),
	path('password_reset/complete/',account_password_reset_complete,name='password_reset_complete'),
	path('signup/', account_sign_up, name='signup'),
	path('wishlist/', account_wishlist, name='wishlist')
]

shop/urls.py
from django.urls import path
from shop.views import index, store_search, product_list, product_detail, item_wished, about_view, contact_view, terms_view, policy_view

urlpatterns = [
    path('', index, name='index'),
    path('search', store_search, name='search'),
    path('products/category/<int:store_cat_id>/<str:store_cat_slug>', product_list, name='store-category-product-list'),
    path('products/sub-category/<int:store_sub_cat_id>/<str:store_sub_cat_slug>', product_list, name='store-sub-category-product-list'),
    path('products/product-category/<int:prod_cat_id>/<str:prod_cat_slug>', product_list, name='product-category-product-list'),
    path('product/<str:product_slug>', product_detail, name='product-detail'),
    path('product/wish/', item_wished, name='wish_product'),
    path('about-us/', about_view, name='about'),
    path('contact-us', contact_view, name='contact'),
    path('terms-and-conditions/', terms_view, name='terms'),
    path('privacy-policy/', policy_view, name='policy'),
]

styl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('affiliate/', include(('affiliate.urls', 'affiliate'), namespace='affiliate')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms
from shop.models import Contact

PRICE_CHOICES = [
    ('5/250', '£5 - £250'),
    ('250/500', '£250 - £500'),
    ('500/750', '£500 - ££750'),
    ('750/1000', '£750 - £1000'),
    ('1000/0', '£1000 +')
]

class ProductListFilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.sizes = kwargs.pop('sizes')
        self.colors = kwargs.pop('colors')
        self.categories = kwargs.pop('categories')
        super(ProductListFilterForm, self).__init__(*args, **kwargs)
        self.fields['categories'] = forms.ChoiceField(choices=self.categories, required=False)
        self.fields['price'] = forms.ChoiceField(choices=PRICE_CHOICES, required=False)
        self.fields['colors'] = forms.MultipleChoiceField(choices=self.colors, required=False)
        self.fields['sizes'] = forms.ChoiceField(choices=self.sizes, required=False)

class SearchForm(forms.Form):
    search = forms.CharField(max_length=512)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

shop/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import ensure_csrf_cookie
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from shop.models import StoreCategory, StoreSubCategory, ProductCategory, Product, ProductColor, StoreBanner
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from shop.forms import ProductListFilterForm, SearchForm, ContactForm
from account.models import WishList
from common.decorators import ajax_required
from django.contrib import messages
# Create your views here.

@ensure_csrf_cookie
def index(request):
    return render(request, 'shop/index.html', {'section' : 'shop_index'})

def store_search(request):
    if not request.is_ajax():
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['search']
        else:
            messages.error(request, 'Search query should not be empty')
            return redirect('shop:index')
    else:
        query = request.GET.get('query')
    items = Product.objects.filter(name__icontains=query, active=True)
    total = items.count()
    paginator = Paginator(items, 6)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        items = paginator.page(paginator.num_pages)
    try:
        search_banner = StoreBanner.objects.get(active=True, location='PS')
    except Exception as e:
        search_banner = None
    if request.is_ajax():
        return render(request, 'shop/items/search_results_ajax.html', {'section' : 'shop_search', 'items' : items})
    return render(request, 'shop/items/search_results.html', {'section' : 'shop_search', 'search_banner' : search_banner, 'items' : items, 'query' : query, 'count' : total})

def product_list(request, store_cat_slug=None, store_cat_id=None, store_sub_cat_slug=None, store_sub_cat_id=None, prod_cat_slug=None, prod_cat_id=None):
    store_category = None
    store_sub_category = None
    product_category = None
    colors = []
    sizes = []
    if store_cat_slug:
        store_category = StoreCategory.objects.get(id=store_cat_id, slug=store_cat_slug)
        items = Product.objects.filter(category__store_sub_category__store_category=store_category)
    if store_sub_cat_slug:
        store_sub_category = StoreSubCategory.objects.get(id=store_sub_cat_id, slug=store_sub_cat_slug)
        items = Product.objects.filter(category__store_sub_category=store_sub_category)
    if prod_cat_slug:
        product_category = ProductCategory.objects.get(id=prod_cat_id, slug=prod_cat_slug)
        items = Product.objects.filter(category=product_category)
    for item in items:
        for color in item.colors.all():
            if color not in colors:
                colors.append(color)
        for size in item.sizes.split(',')[:-1]:
            if size not in sizes:
                sizes.append(size)
    categories_tup = []
    sizes_tup = []
    colors_tup = []
    if store_category:
        for cat in store_category.store_sub_categories.all():
            choice = ('1/{}'.format(cat.id), cat.name)
            categories_tup.append(choice)
    elif store_sub_category:
        for cate in store_sub_category.categories.all():
            choice = ('2/{}'.format(cate.id), cate.name)
            categories_tup.append(choice)
    for siz in sizes:
        choice = (siz, siz)
        sizes_tup.append(choice)
    for colo in colors:
        choice = (colo.slug, colo.name)
        colors_tup.append(choice)
    if request.method == 'POST':
        filtered_items = []
        form = ProductListFilterForm(data=request.POST, categories=categories_tup, colors=colors_tup, sizes=sizes_tup)
        if form.is_valid():
            _filter = form.cleaned_data
            category_filter = _filter['categories'].split('/')
            try:
                if category_filter[0] == '1':
                    items = items.filter(category__store_sub_category__store_category=StoreCategory.objects.get(id=int(category_filter[1])))
                elif category_filter[1] == '1':
                    items = items.filter(category__store_sub_category=StoreSubCategory.objects.get(id=int(category_filter[1])))
                price_filter = _filter['price'].split('/')
            except IndexError as e:
                pass
            price_filter = _filter['price'].split('/')
            try:
                if int(price_filter[1]) == 0:
                    for price_f_item in items.filter(sale_price__gte=float(price_filter[0])):
                        fil
                else:
                    items = items.filter(sale_price__gte=float(price_filter[0]), sale_price__lte=float(price_filter[1]))
            except IndexError as e:
                pass
            colors_filter = _filter['colors']
            colors_f = []
            for color_f in colors_filter:
                colors_f.append(ProductColor.objects.get(slug=color_f))
            if len(colors_f) > 0:
                items = items.filter(colors__in=colors_f)
            size_filter = _filter['sizes']
            items = items.filter(sizes__icontains=size_filter)
    else:
        form = ProductListFilterForm(categories=categories_tup, colors=colors_tup, sizes=sizes_tup)
    items = items.distinct()
    total = items.count()
    paginator = Paginator(items, 6)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        items = paginator.page(paginator.num_pages)
    try:
        list_banner = StoreBanner.objects.get(active=True, location='PL')
    except Exception as e:
        list_banner = None
    if request.is_ajax():
        return render(request, 'shop/items/list_ajax.html', {'section' : 'shop_list', 'list_banner' : list_banner, 'form' : form, 'store_category' : store_category, 'store_sub_category' : store_sub_category, 'product_category' : product_category, 'items' : items})
    return render(request, 'shop/items/list.html', {'section' : 'shop_list', 'list_banner' : list_banner, 'form' : form, 'store_category' : store_category, 'store_sub_category' : store_sub_category, 'product_category' : product_category, 'items' : items})

def product_detail(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    sizes = product.sizes.split(',')[:-1]
    images = product.images.all()
    try:
        detail_banner = StoreBanner.objects.get(active=True, location='PD')
    except Exception as e:
        detail_banner = None
    return render(request, 'shop/items/detail.html', {'section' : 'shop_detail', 'detail_banner' : detail_banner, 'product' : product, 'sizes' : sizes, 'images' : images})

@ajax_required
@require_POST
@login_required
def item_wished(request):
	item_id = request.POST.get('id')
	action = request.POST.get('action')
	if item_id and action:
		try:
			item = Product.objects.get(id=int(item_id))
			if action == 'wish':
				item.wished.add(request.user)
				WishList.objects.create(user=request.user, item=item)
			else:
				item.wished.remove(request.user)
				WishList.objects.get(user=request.user, item=item).delete()
			return JsonResponse({'status' : 'ok'})
		except:
			pass
	return JsonResponse({'status' : 'ko'})

def about_view(request):
    return render(request, 'shop/about.html', {'section' : 'shop_about'})

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Thank you for your message, we will contact you soon.")
            return redirect('shop:index')
    else:
        form = ContactForm()
    return render(request, 'shop/contact.html', {'section' : 'shop_contact', 'form' : form})

def policy_view(request):
    return render(request, 'shop/policy.html', {'section' : 'shop_policy'})

def terms_view(request):
    return render(request, 'shop/terms.html', {'section' : 'shop_terms'})

shop/templates/banner.html
<div class="hero__section slice" style="background-image: url({{banner.image.url}});">
    <div class="hero__section-content">
        <div class="hero__section-slider text-white">
            <div class="mb-2 text-shadow">
                <h2 class="h2">Our STYL Collections</h2>
            </div>
            <div class="owl-carousel hero__section-slide">
                {% for category in store_sub_categories %}
                <a href="#" class="item">
                    <div class="item__content">
                        {% if category.image %}
                        <img src="{{ category.image.url }}" class="icon" alt="">
                        {% else %}
                        <svg class="icon"><use xlink:href="{{ category.icon }}" /></svg>
                        {% endif %}
                    </div>
                    <span>{{ category.name }}</span>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

shop/templates/base.html
{% load staticfiles %}
{% load store_base %}
{% load filter_extras %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Styl</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/static/build/img/favicon.png" type="image/x-icon">
        <link rel="icon" href="/static/build/img/favicon.png" type="image/x-icon">
        {% if section == "shop_index" %}
        <link rel="stylesheet" href="/static/build/css/pages/landing.css">
        {% elif section == "shop_list" or section == "shop_search" %}
        <link rel="stylesheet" href="/static/build/css/pages/list.css">
        {% elif section == "shop_detail" %}
        <link rel="stylesheet" href="/static/build/css/pages/view.css">
        {% elif section == "shop_contact" or section == "shop_about" %}
        <link rel="stylesheet" href="/static/build/css/pages/contact.css">
        {% else %}
        <link rel="stylesheet" href="/static/build/css/pages/account.css">
        {% endif %}
    </head>

    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        <header class="header">
            <div class="header__tp-xs">
                <div class="container">
                    <div class="row">
                        <div class="col-3">
                            <a href="#" class="nav__toggle-xs"><i class="fa fa-bars"></i><i class="fa fa-close"></i></a>
                        </div>
                        <div class="col-9 text-right">
                            <ul class="list-inline">
                                <li>
                                    <a href="#" class="search-xs"><i class="fa fa-search"></i></a>
                                </li>
                                {% if request.user.is_authenticated %}
                                <li>
                                    <a title="Sign Out" href="{% url 'account:logout' %}">
                                        <i class="fa fa-sign-out"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'account:wishlist' %}" class="count">
                                        <span class="count__number">{{ arg|get_wishlist_count:request.user }}</span>
                                        <i class="fa fa-heart"></i>
                                    </a>
                                </li>
                                {% else %}
                                <li>
                                    <a href="{% url 'account:login' %}"><i class="fa fa-user"></i></a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="header__tp-xs-search">
                        {% show_search_xs store_base %}
                    </div>
                </div>
            </div>
            <div class="header__bt">
                <div class="container">
                    <div class="header__bt-lt">
                        {% show_search store_base %}
                    </div>
                    <div class="header__bt-logo">
                        <a href="/"><img src="/static/build/img/logo.svg" alt=""></a>
                    </div>
                    <div class="header__bt-rt">
                        <ul class="list-inline">
                            {% if request.user.is_authenticated %}
                            <li>
                                <a title="Sign Out" href="{% url 'account:logout' %}">
                                    <i class="fa fa-sign-out"></i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'account:wishlist' %}" class="count">
                                    <span class="count__number">{{ arg|get_wishlist_count:request.user }}</span>
                                    <i class="fa fa-heart"></i>
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a href="{% url 'account:login' %}"><i class="fa fa-user"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <nav class="navigation">
                <div class="container">
                    {% show_menu store_base %}
                </div>
            </nav>
        </header>

        {% block content %}{% endblock %}

        <footer>
            <div class="container text-center">
                <img src="/static/build/img/logo-inverse.svg" class="footer-logo" alt="">
                <ul class="list-inline mb-1">
                    <li><a href="{% url 'shop:about' %}">About</a></li>
                    <li><a href="{% url 'shop:terms' %}">Terms & Conditions</a></li>
                    <li><a href="{% url 'shop:policy' %}">Privacy Policy</a></li>
                    <li><a href="{% url 'shop:contact' %}">Contact</a></li>
                </ul>
                <ul class="list-inline social">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                </ul>
                <div class="copyright">
                    <span>All rights reserved. 2018.</span>
                </div>
            </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script>
            $('.alert-dismiss').click(function(){$(this).parent().fadeOut();});
            function csrfSafeMethod(e){return/^(GET|HEAD|OPTIONS|TRACE)$/.test(e)}var csrftoken=$.cookie("csrftoken");$.ajaxSetup({beforeSend:function(e,t){csrfSafeMethod(t.type)||this.crossDomain||e.setRequestHeader("X-CSRFToken",csrftoken)}});
            $(document).ready(function(){$(".wish-btn").click(function(){var t=$(this).attr("data-id"),a=$(this).attr("data-action"),i=$(this);$.post("/product/wish/",{id:t,action:a},function(t){"ok"==t.status&&"wish"==a?(i.attr("data-action","unwish"),i.addClass("wished"),$('.count__number').each(function(){$(this).text(parseInt($(this).text())+1)}),""!=i.text()&&i.html('<i class="fa fa-heart"></i> Remove from Wishlist')):(i.attr("data-action","wish"),i.removeClass("wished"),$('.count__number').each(function(){$(this).text(parseInt($(this).text())-1)}),""!=i.text()&&i.html('<i class="fa fa-heart"></i> Add to Wishlist'))})})});
        </script>
    </body>
</html>

shop/templates/category_banners.html
<section class="category-section">
    <div class="grid__row mb-3">
        {% if banner_tl %}
        <div class="grid-6 grid-xs-12">
            <div class="img-container img__top">
                <img src="{{ banner_tl.image.url }}" alt="">
                <div class="img-container-content img-container-content-1">
                    <div class="text-center">
                        <h2 class="h2 h-break text-shadow">{{ banner_tl.title }}</h2>
                        <a href="{{ banner_tl.get_absolute_url }}" class="btn btn-lg btn-white">{{ banner_tl.btn_text }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% if banner_tr %}
        <div class="grid-6 grid-xs-12">
            <div class="img-container img__top">
                <img src="{{ banner_tr.image.url }}" alt="">
                <div class="img-container-content img-container-content-1">
                    <div class="text-center">
                        <h2 class="h2 h-break text-shadow">{{ banner_tr.title }}</h2>
                        <a href="{{ banner_tr.get_absolute_url }}" class="btn btn-lg btn-white">{{ banner_tr.btn_text }}</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% if banner_cl %}
    <div class="img-container mb-3">
        <img src="{{ banner_cl.image.url }}" alt="">
        <div class="img-container-content img-container-content-2 text-white">
            <div class="mb-2 text-shadow">
                <h2 class="h2">{{ banner_cl.title }}</h2>
                <p class="font-lg">{{ banner_cl.caption }}</p>
            </div>
            <a href="{{ banner_cl.get_absolute_url }}" class="btn btn-lg btn-white">{{ banner_cl.btn_text }}</a>
        </div>
    </div>
    {% endif %}
    <div class="grid__row">
        {% if banner_bl %}
        <div class="grid-6 grid-xs-12">
            <div class="img-container img__bottom">
                <img src="{{ banner_bl.image.url }}" alt="">
                <div class="img-container-content img-container-content-3">
                    <div class="mb-1 text-shadow">
                        <h2 class="h2">{{ banner_bl.title }}</h2>
                        <p class="font-md">{{ banner_bl.caption }}</p>
                    </div>
                    <a href="{{ banner_bl.get_absolute_url }}" class="btn btn-white">{{ banner_bl.btn_text }}</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% if banner_br %}
        <div class="grid-6 grid-xs-12">
            <div class="img-container img__bottom">
                <img src="{{ banner_br.image.url }}" alt="">
                <div class="img-container-content img-container-content-3 img-container-content-4">
                    <div class="mb-1 text-shadow">
                        <h2 class="h2">{{ banner_br.title }}</h2>
                    </div>
                    <a href="{{ banner_br.get_absolute_url }}" class="btn btn-white">{{ banner_br.btn_text }}</a>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</section>

shop/templates/menu.html
<ul class="navigation__nav">
    {% for store_category in store_categories %}
    <li>
        <a href="Javascript:void(0)">{{ store_category.name }}</a>
        <div class="megamenu__container">
            {% for store_sub_category in store_sub_categories %}
            {% if store_sub_category.store_category == store_category %}
            <div class="megamenu__container-col">
                <a href="{{ store_sub_category.get_absolute_url }}">
                        <h5 class="h5 text-black oswald text-uppercase mb-2">{{ store_sub_category.name }}</h5>
                    {% if store_sub_category.image %}
                    <img src="{{ store_sub_category.image.url }}" class="icon">
                    {% endif %}
                </a>
                <ul class="list">
                    {% for product_category in product_categories %}
                    {% if product_category.store_sub_category == store_sub_category %}
                    <li><a href="{{ product_category.get_absolute_url }}">{{ product_category.name }}</a></li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </li>
    {% endfor %}
</ul>

shop/templates/search.html
<div class="input-icon">
    <form action="{% url 'shop:search' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Search" class="form-control" name="search">
        <span><button><i class="fa fa-search"></i></button></span>
    </form>
</div>

shop/templates/search_xs.html
<div class="input-icon">
    <form action="{% url 'shop:search' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Search" class="form-control" name="search">
        <span>
            <a href="#" class="header__tp-xs-search-close"><i class="fa fa-close"></i></a>
        </span>
    </form>
</div>